"""Keep the Studio's original Phosphor glyphs, with only the icons it uses.

Regenerate after adding icons:
  python3 -m pip install 'fonttools[woff]'
  python3 scripts/subset-studio-icons.py
The generated files are committed, so application builds need only npm ci.
"""
from pathlib import Path
import re
from fontTools import subset

root = Path(__file__).resolve().parent.parent
source = root / 'node_modules/@phosphor-icons/web/src/regular'
css = (source / 'style.css').read_text()
characters = dict(re.findall(r'\.ph\.ph-([a-z0-9-]+):before\s*\{\s*content: "\\([0-9a-f]+)";', css))
files = [root / 'playground/index.html', *sorted((root / 'playground/src').rglob('*.js'))]
icons = sorted(set(re.findall(r'ph-([a-z][a-z0-9]*(?:-[a-z0-9]+)*)', '\n'.join(file.read_text() for file in files))))
missing = [icon for icon in icons if icon not in characters]
if missing:
    raise ValueError(f'Unknown Phosphor icons: {missing}')
options = subset.Options()
options.flavor = 'woff2'
font = subset.load_font(str(source / 'Phosphor.ttf'), options)
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=[int(characters[icon], 16) for icon in icons])
subsetter.subset(font)
output = root / 'playground/src/fonts'
output.mkdir(exist_ok=True)
subset.save_font(font, str(output / 'phosphor-studio.woff2'), options)
(output / 'Phosphor-LICENSE.txt').write_text((source.parent.parent / 'LICENSE').read_text())
style = '''/* Original Phosphor Regular glyphs, MIT licensed. Generated by subset-studio-icons.py. */
@font-face {
  font-family: 'Phosphor Studio';
  src: url('./fonts/phosphor-studio.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
.ph {
  font-family: 'Phosphor Studio' !important;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  letter-spacing: 0;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
'''
style += '\n'.join(f'.ph.ph-{icon}::before {{ content: "\\{characters[icon]}"; }}' for icon in icons) + '\n'
(root / 'playground/src/icons.css').write_text(style)
print(f'Generated {len(icons)} original Phosphor glyphs ({(output / "phosphor-studio.woff2").stat().st_size:,} bytes).')
